export default function() {
    return [
        {
            id: 1,
            firstName: "Elon",
            lastName: "Musk",
            organisation: "Tesla",
            dateOfBirth: "28.06.1971.",
            placeOfBirth: "Pretoria, South Africa",
            img: "https://cdnassets.hw.net/03/ac/c043ba6040ba9d8e1d22240825b7/elon-musk-the-summit-2013.jpg",
        },
        {
            id: 2,
            firstName: "Mark",
            lastName: "Zuckerberg",
            organisation: "Facebook",
            dateOfBirth: "14.05.1984.",
            placeOfBirth: "New York, U.S.A.",
            img: "https://s.yimg.com/ny/api/res/1.2/LtJiCtUaitfokY6Pmw5W6w--~A/YXBwaWQ9aGlnaGxhbmRlcjtzbT0xO3c9ODAw/http://media.zenfs.com/en-US/homerun/time_72/2c6c973837e3cfb88d95598e574141c0",
        },
        {
            id: 3,
            firstName: "Jeff",
            lastName: "Bezos",
            organisation: "Amazon",
            dateOfBirth: "12.01.1964.",
            placeOfBirth: "Albuquerque, U.S.A.",
            img: "https://www.intouchweekly.com/wp-content/uploads/2019/01/jeff-bezos-5.jpg?resize=800%2C800",
        },
        {
            id: 4,
            firstName: "Bill",
            lastName: "Gates",
            organisation: "Microsoft",
            dateOfBirth: "28.10.1955.",
            placeOfBirth: "Seattle, U.S.A.",
            img: "https://yt3.ggpht.com/a/AGF-l7--eTcViDzx49fKfHCcixMdBgFVYXwQtrbvBQ=s800-mo-c-c0xffffffff-rj-k-no",
        },
        {
            id: 5,
            firstName: "Bernard",
            lastName: "Arnault",
            organisation: "Louis Vuitton SE",
            dateOfBirth: "05.03.1949.",
            placeOfBirth: "Roubaix, France",
            img: "http://dirigeants-entreprise.com/images/t5534-800-800-50.jpg",
        },
        {
            id: 6,
            firstName: "Warren",
            lastName: "Buffet",
            organisation: "Berkshire Hathaway",
            dateOfBirth: "30.08.1930.",
            placeOfBirth: "Omaha, U.S.A.",
            img: "https://nonprofitchroniclesdotcom.files.wordpress.com/2017/03/warren-buffett.jpg",
        },
        {
            id: 7,
            firstName: "Larry",
            lastName: "Ellison",
            organisation: "Oracle Corporation",
            dateOfBirth: "17.08.1944.",
            placeOfBirth: "New York, U.S.A.",
            img: "https://asset.barrons.com/public/resources/images/BN-UR804_201708_G_20170815155843.jpg",
        },
        {
            id: 8,
            firstName: "Amancio",
            lastName: "Ortega",
            organisation: "Inditex",
            dateOfBirth: "28.03.1936.",
            placeOfBirth: "León, Spain",
            img: "https://www.zetaestaticos.com/leon/img/noticias/0/961/961005_1.jpg",
        },
        {
            id: 9,
            firstName: "Carlos",
            lastName: "Slim",
            organisation: "Grupo Carso",
            dateOfBirth: "28.01.1940.",
            placeOfBirth: "Mexico City, Mexico",
            img: "https://ocdn.eu/pulscms-transforms/1/yePktkqTURBXy9kNGRhYmVkNjY0ZDg3YzAxOTI4NWNiMGVhOWJlZDRkMy5qcGVnkpUCzQPAAMLDlQIAzQPAwsM",
        },
        {
            id: 10,
            firstName: "Françoise",
            lastName: "Bettencourt Meyers",
            organisation: "L'Oréal",
            dateOfBirth: "10.07.1953.",
            placeOfBirth: "Neuilly-sur-Seine, France",
            img: "https://cache.bzi.ro/cache/9/224/c800x800_Francoise_Bettencourt_Meyers.jpg",
        },
        {
            id: 11,
            firstName: "Michael",
            lastName: "Bloomberg",
            organisation: "Bloomberg L.P",
            dateOfBirth: "14.02.1942.",
            placeOfBirth: "Boston, U.S.A.",
            img: "https://commencement.wustl.edu/wp-content/uploads/2014/01/mike_bloomberg_headshot.jpg",
        },
        {
            id: 12,
            firstName: "Mukesh",
            lastName: "Ambani",
            organisation: "Reliance Industries Limited",
            dateOfBirth: "19.04.1957.",
            placeOfBirth: "Aden, Yemen",
            img: "https://indiantelevision.com/sites/default/files/styles/230x230/public/images/tv-images/2018/10/17/am.jpg?itok=GxrhDYsg",
        },
        {
            id: 13,
            firstName: "Larry",
            lastName: "Page",
            organisation: "Google",
            dateOfBirth: "26.03.1973.",
            placeOfBirth: "Lansing, U.S.A.",
            img: "https://img.europapress.es/fotoweb/fotonoticia_20081024120111_800.jpg",
        },
        {
            id: 14,
            firstName: "Jim",
            lastName: "Walton",
            organisation: "Walmart",
            dateOfBirth: "07.06.1948.",
            placeOfBirth: "Newport, U.S.A.",
            img: "https://54below.com/app/uploads/Walton-Jim.png",
        },
        {
            id: 15,
            firstName: "Steve",
            lastName: "Jobs",
            organisation: "Apple",
            dateOfBirth: "24.02.1955.",
            placeOfBirth: "San Francisco, U.S.A.",
            img: "https://static1.i4u.com/sites/default/files/imagecache/main_image_google_topstories1x1/images/2009/stevejobs-4u.jpg",
        },
    ]
}